### ISSUE TITLE
animate rigged human

### ISSUE THREAD

**Issue by wuneng** [googleinterns/humangps#2]
Hi,@feitongt 

Suppose I already have a rigged human body model and body pose sequence collected from Mixamo, how to animate the rigged model? 
Thanks.

**Comment by feitongt** [comment]
Hi @wuneng 

Mixamo supports uploading your own characters and adding animations to characters directly, or you can use 3D software or renderers such as Blender, Unity, or UE to retarget the rigged models. And you can find some tutorials on the Youtube.

Best,
